
services:
  mongollm:
    image: mongo:latest
    container_name: mongollm
    ports:
      - "27017:27017"

  client:
    image: llm-app
    build:
      dockerfile: dockerfile
    ports:
      - "8503:8503"
    volumes:
      - ./data:/data
    environment:
      MONGO_HOST: mongollm
      DOCKER_ENV: true
      SQLITE_DB_PATH: /data/chatbot.db
      REACT_APP_CHROMA_SERVER_URL: "http://localhost:8000"
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      HF_TOKEN: ${HF_TOKEN}