version: '3'

services:
  mongo:
    image: mongo:latest
    container_name: mongollm
    ports:
      - "27017:27017"

  postgres:
    container_name: llmPostgres
    image: postgres:latest
    ports:
      - "32003:5432"  # Ensure the correct port is exposed
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/01_init.sql
    environment:
      POSTGRES_DB: llm
      POSTGRES_USER: llm
      POSTGRES_PASSWORD: llm
      POSTGRES_INITDB_ARGS: "--auth-local=trust --auth-host=trust"

  # client:
  #   image: llm-app
  #   build:
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8503:8503"
  #   environment:
  #       MONGO_HOST: mongollm
  #       DOCKER_ENV: true
  #       POSTGRES_HOST: llmPostgres  # Use the correct service name
  #       POSTGRES_USER: llm
  #       POSTGRES_PASSWORD: llm
  #       POSTGRES_DBNAME: llm
  #       POSTGRES_PORT: 5432  # Use the correct port
  #       REACT_APP_CHROMA_SERVER_URL: "http://localhost:8000"
  #       MISTRAL_API_KEY: ${MISTRAL_API_KEY}
  #       HF_TOKEN: ${HF_TOKEN}